"""Customer + customer-level membership — FR-WKS-001/005.

create_customer_with_owner is deliberately NOT exposed over the public API
(api/): section 2.3 lists "Self-serve billing va public signup" as
explicitly OUT OF SCOPE for v1. A new Customer is provisioned by an
operator (Platform Owner tooling, FR-ADM-001 — not yet built) or a test
fixture, never by an anonymous HTTP caller. Membership management below
(invite/role-change/remove within an EXISTING customer) is a different,
in-scope action and does get an API (api/workspace_admin.py).
"""

import dataclasses
import uuid

from sqlalchemy import select
from sqlalchemy.exc import IntegrityError
from sqlalchemy.ext.asyncio import AsyncSession

from doda.application.audit_service import record_audit_event
from doda.domain.customer.models import Customer, CustomerMembership, UserCustomerIndex
from doda.domain.identity.models import User
from doda.domain.security.roles import CustomerRole
from doda.domain.workspace.models import WorkspaceMembership


class CustomerMembershipError(Exception):
    """A well-formed request that violates a business rule — e.g. removing
    or demoting the last customer_owner (FR-WKS-005: "oxirgi Owner chiqarib
    bo'lmaydi"). Distinct from AuthorizationError: not about permissions."""


class DuplicateMembershipError(Exception):
    """Raised by invite_customer_member when the user already has a
    CustomerMembership row for this customer. Without this check, two
    rapid invite calls (a double-clicked "Qo'shish" button, or two admins
    inviting the same person at once) would each insert their own
    CustomerMembership row — customer_memberships has no unique constraint
    on (customer_id, user_id), so nothing else stops it — leaving the same
    person listed twice in list_customer_members, each row independently
    editable/removable."""


async def create_customer_with_owner(
    session: AsyncSession, *, customer_id: uuid.UUID, name: str, owner_user_id: uuid.UUID, actor_id: str
) -> tuple[Customer, CustomerMembership]:
    """FR-WKS-001. `customer_id` must be pre-generated by the caller, who
    must have already opened tenant_scoped_session(customer_id) with that
    SAME id before calling this — Customer has no RLS of its own (it's the
    tenant root), but CustomerMembership does, so the insert below only
    succeeds if the session's GUC already matches. See
    tests/integration/conftest.py for the established pattern.
    """
    customer = Customer(id=customer_id, name=name)
    session.add(customer)
    await session.flush()

    membership = CustomerMembership(
        customer_id=customer_id, user_id=owner_user_id, role=CustomerRole.CUSTOMER_OWNER.value
    )
    session.add(membership)
    # See UserCustomerIndex's docstring: written in the same transaction as
    # the CustomerMembership row it mirrors, never independently.
    session.add(UserCustomerIndex(user_id=owner_user_id, customer_id=customer_id))
    await session.flush()

    await record_audit_event(
        session,
        customer_id=customer_id,
        trace_id=uuid.uuid4(),
        actor_id=actor_id,
        event_type="customer.created.v1",
        safe_metadata={"customer_id": str(customer_id), "name": name},
    )
    return customer, membership


async def _count_customer_owners(session: AsyncSession, customer_id: uuid.UUID) -> int:
    # with_for_update(): two owners concurrently removing/demoting EACH
    # OTHER (e.g. both acting at once while a customer still has exactly
    # two owners) would otherwise both count 2, both pass the "more than
    # one left" check below, and both proceed — leaving zero owners, with
    # no customer_owner left to ever invite a new one. Locking these rows
    # serializes the two calls: the second one, once unblocked, re-counts
    # under the first call's already-committed change and correctly sees
    # only one owner left. Same SELECT ... FOR UPDATE technique as the
    # Task/Action concurrency fixes (task_service.change_task_status,
    # action_service.apply_transition) — kill_switch_service's engage races
    # use a different mechanism (begin_nested + IntegrityError recovery),
    # since those are insert races, not a check against existing rows.
    result = await session.execute(
        select(CustomerMembership)
        .where(
            CustomerMembership.customer_id == customer_id,
            CustomerMembership.role == CustomerRole.CUSTOMER_OWNER.value,
        )
        .with_for_update()
    )
    return len(result.scalars().all())


async def invite_customer_member(
    session: AsyncSession, *, customer_id: uuid.UUID, user_id: uuid.UUID, role: CustomerRole, actor_id: str
) -> CustomerMembership:
    membership = CustomerMembership(customer_id=customer_id, user_id=user_id, role=role.value)
    try:
        async with session.begin_nested():
            session.add(membership)
            await session.flush()
    except IntegrityError as exc:
        # Matches action_service.propose_action's idempotency-key handling:
        # the unique constraint on (customer_id, user_id) is the actual
        # race-safe guard (two concurrent invites, or one double-clicked
        # "Qo'shish"); this turns that into a clean, expected error instead
        # of a raw 500 — unlike propose_action's replay semantics, a
        # duplicate invite is a genuine "already a member" business error,
        # not something to silently treat as the same request repeated.
        raise DuplicateMembershipError("user is already a member of this customer") from exc

    existing_index_row = await session.get(
        UserCustomerIndex, {"user_id": user_id, "customer_id": customer_id}
    )
    if existing_index_row is None:
        session.add(UserCustomerIndex(user_id=user_id, customer_id=customer_id))
        await session.flush()
    await record_audit_event(
        session,
        customer_id=customer_id,
        trace_id=uuid.uuid4(),
        actor_id=actor_id,
        event_type="customer.member_invited.v1",
        safe_metadata={"customer_membership_id": str(membership.id), "role": role.value},
    )
    return membership


async def change_customer_member_role(
    session: AsyncSession, membership: CustomerMembership, *, new_role: CustomerRole, actor_id: str
) -> CustomerMembership:
    if (
        membership.role == CustomerRole.CUSTOMER_OWNER.value
        and new_role is not CustomerRole.CUSTOMER_OWNER
        and await _count_customer_owners(session, membership.customer_id) <= 1
    ):
        raise CustomerMembershipError("cannot demote the last customer_owner")

    previous_role = membership.role
    membership.role = new_role.value
    await session.flush()
    await record_audit_event(
        session,
        customer_id=membership.customer_id,
        trace_id=uuid.uuid4(),
        actor_id=actor_id,
        event_type="customer.member_role_changed.v1",
        safe_metadata={
            "customer_membership_id": str(membership.id),
            "from_role": previous_role,
            "to_role": new_role.value,
        },
    )
    return membership


async def remove_customer_member(
    session: AsyncSession, membership: CustomerMembership, *, actor_id: str
) -> None:
    """Also removes every WorkspaceMembership derived from this
    CustomerMembership in the same transaction: WorkspaceMembership has no
    FK on customer_membership_id (6.2: no cross-domain FK, ID-reference
    only), so without this cleanup a removed customer member would leave
    orphaned workspace memberships an authz lookup could still resolve."""
    if (
        membership.role == CustomerRole.CUSTOMER_OWNER.value
        and await _count_customer_owners(session, membership.customer_id) <= 1
    ):
        raise CustomerMembershipError("cannot remove the last customer_owner")

    orphaned = await session.execute(
        select(WorkspaceMembership).where(WorkspaceMembership.customer_membership_id == membership.id)
    )
    for workspace_membership in orphaned.scalars():
        await session.delete(workspace_membership)

    await record_audit_event(
        session,
        customer_id=membership.customer_id,
        trace_id=uuid.uuid4(),
        actor_id=actor_id,
        event_type="customer.member_removed.v1",
        safe_metadata={"customer_membership_id": str(membership.id), "role": membership.role},
    )
    removed_user_id, removed_customer_id = membership.user_id, membership.customer_id
    await session.delete(membership)
    await session.flush()

    # Only drop the bootstrap index row once no OTHER CustomerMembership
    # row remains for this (user, customer) pair — nothing prevents more
    # than one such row today (see UserCustomerIndex's docstring), and a
    # stray extra one must keep the user discoverable via GET /v1/me/workspaces.
    remaining = await session.scalar(
        select(CustomerMembership).where(
            CustomerMembership.user_id == removed_user_id,
            CustomerMembership.customer_id == removed_customer_id,
        )
    )
    if remaining is None:
        index_row = await session.get(
            UserCustomerIndex, {"user_id": removed_user_id, "customer_id": removed_customer_id}
        )
        if index_row is not None:
            await session.delete(index_row)
            await session.flush()


@dataclasses.dataclass(frozen=True)
class CustomerMemberEntry:
    membership_id: uuid.UUID
    user_id: uuid.UUID
    display_name: str
    role: str


async def list_customer_members(
    session: AsyncSession, *, customer_id: uuid.UUID
) -> list[CustomerMemberEntry]:
    """There was no way to see who is actually in a customer at all before
    this — invite/change-role/remove all existed, but nothing to list the
    current roster, the same class of gap closed for workspace members
    (workspace_service.list_workspace_members) and elsewhere in this API."""
    rows = await session.execute(
        select(CustomerMembership, User.display_name)
        .join(User, User.id == CustomerMembership.user_id)
        .where(CustomerMembership.customer_id == customer_id)
    )
    return [
        CustomerMemberEntry(
            membership_id=membership.id,
            user_id=membership.user_id,
            display_name=display_name,
            role=membership.role,
        )
        for membership, display_name in rows
    ]
